# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGqd2yJZ-4T4A5ldpJNTL3Xxmqzlloob
"""

import numpy as np
import matplotlib.pyplot as plt

# PV panel reference parameters (at STC: 1000 W/m², 25 °C)
Isc_ref = 8.0    # Short-circuit current (A)
Voc_ref = 37.0   # Open-circuit voltage (V)
T_ref = 25.0     # Reference temperature (°C)
G_ref = 1000.0   # Reference irradiance (W/m²)

# Temperature coefficients
alpha_Isc = 0.005   # A/°C (Isc increases slightly with T)
beta_Voc = -0.12    # V/°C (Voc decreases with T)

def pv_model(G, T_C, Npoints=200):
    """
    Compute simplified I-V curve for a PV panel
    Inputs:
      G : irradiance (W/m²)
      T_C : cell temperature (°C)
    """
    # Adjust Isc with irradiance and temperature
    Isc = Isc_ref * (G / G_ref) + alpha_Isc * (T_C - T_ref)
    # Adjust Voc with temperature
    Voc = Voc_ref + beta_Voc * (T_C - T_ref)

    V = np.linspace(0, Voc, Npoints)
    # Simple exponential-like shape: I = Isc * (1 - exp(k*V/Voc))
    k = 5  # shaping factor
    I = Isc * (1 - np.exp(k * (V - Voc) / Voc))
    I[I < 0] = 0   # clamp to zero

    P = V * I
    return V, I, P

# --------------------------
# Simulation
irradiances = [200, 600, 1000]   # at fixed 25°C
temperatures = [0, 25, 50]       # at fixed 1000 W/m²

# Plot I-V for irradiance sweep
plt.figure()
for G in irradiances:
    V, I, P = pv_model(G, 25)
    plt.plot(V, I, label=f"G={G} W/m², T=25°C")
plt.xlabel("Voltage (V)")
plt.ylabel("Current (A)")
plt.title("I-V Curves under Different Irradiance")
plt.legend()
plt.grid(True)
plt.show()

# Plot P-V for irradiance sweep
plt.figure()
for G in irradiances:
    V, I, P = pv_model(G, 25)
    plt.plot(V, P, label=f"G={G} W/m², T=25°C")
plt.xlabel("Voltage (V)")
plt.ylabel("Power (W)")
plt.title("P-V Curves under Different Irradiance")
plt.legend()
plt.grid(True)
plt.show()

# Plot I-V for temperature sweep
plt.figure()
for T in temperatures:
    V, I, P = pv_model(1000, T)
    plt.plot(V, I, label=f"G=1000 W/m², T={T}°C")
plt.xlabel("Voltage (V)")
plt.ylabel("Current (A)")
plt.title("I-V Curves under Different Temperature")
plt.legend()
plt.grid(True)
plt.show()

# Plot P-V for temperature sweep
plt.figure()
for T in temperatures:
    V, I, P = pv_model(1000, T)
    plt.plot(V, P, label=f"G=1000 W/m², T={T}°C")
plt.xlabel("Voltage (V)")
plt.ylabel("Power (W)")
plt.title("P-V Curves under Different Temperature")
plt.legend()
plt.grid(True)
plt.show()